version: "3.8"

services:

  postgres:
    image: postgres:17.4
    container_name: wallet-postgres
    restart: unless-stopped
    user: ${DB_POSTGRES_USER}
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - ${DB_POSTGRES_PORT}:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - intranet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: ${DOCKER_HEALTHCHECK_INTERVAL}
      retries: ${DOCKER_HEALTHCHECK_RETRIES}
      timeout: ${DOCKER_HEALTHCHECK_TIMEOUT}
    deploy:
      resources:
        limits:
          memory: 1GB

networks:
  intranet:
    driver: bridge