export const APP_IDS_LENGHT = 36

export const ONE_MINUTE_IN_MS = 60000
export const ONE_HOUR_IN_MS = ONE_MINUTE_IN_MS * 60
export const ONE_DAY_IN_MS = ONE_HOUR_IN_MS * 24
export const ONE_MONTH_IN_MS = ONE_DAY_IN_MS * 30

export const ACCESS_TOKEN_EXPIRE_IN_MS = ONE_HOUR_IN_MS
export const ACCESS_TOKEN_EXPIRE_IN_SECONDS = ACCESS_TOKEN_EXPIRE_IN_MS/1000
export const ACCESS_TOKEN_EXPIRE_IN_DAYS = 1/24

export const REFRESH_TOKEN_EXPIRE_IN_MS = ONE_MONTH_IN_MS
export const REFRESH_TOKEN_EXPIRE_IN_SECONDS = REFRESH_TOKEN_EXPIRE_IN_MS/1000
export const REFRESH_TOKEN_EXPIRE_IN_DAYS = 30

export const ACCESS_TOKEN_COOKIE_KEY = 'access_token'
export const SESSION_COOKIE_KEY = 'session'
